28/07/21 (01:12:50) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 919, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
10/09/21 (13:31:28) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2939, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3971, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2719, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
ValueError: Sign not allowed in string format specifier
10/09/21 (13:31:28) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

11/09/21 (14:00:02) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:01:31) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:01:59) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:02:12) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:02:18) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (15:19:51) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2939, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3971, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2618, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
11/09/21 (15:19:53) | WARNING: Exiting with errorcode (1). Runtime 1:02:06 

